version: '3.8'

services:
  django:
    build: .
    container_name: django-app
    restart: unless-stopped
    ports:
      - "3015:3015"
    env_file:
      - .env
    depends_on:
      - redis-django
    command: python manage.py runserver 0.0.0.0:3015
    #command: gunicorn descriptive_analysis.wsgi:application --bind 0.0.0.0:3015 --workers 4 (Produccion)

  redis-django:
    image: redis:6.2-alpine
    container_name: redis-django
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - ./evaluation/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

networks:
  default:
    name: django-net
